export default {
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  EMAIL_FROM: 'EMAIL_FROM',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
};
